using System;
using NUnit.Framework;

[TestFixture]
class Example3
{
    private Mock<IEnumerable<int>> _d;
    private Example3 _example3;
    [Test]
    public void Function1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Assert.Fail("autogenerated");
    }
}