using System;
using NUnit.Framework;

[TestFixture]
class Example3
{
    private Mock<IEnumerable<int>> _d;
    private Example3 _example3;
    [SetUp]
    public void SetUp()
    {
        d = new IEnumerable<int>();
        _example3 = new Example3(d);
    }

    [Test]
    public void Function1()
    {
        var a = default (int);
        var b = default (string);
        Function1(a, b);
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Function2();
        Assert.Fail("autogenerated");
    }
}