using System;
using NUnit.Framework;

[TestFixture]
class Example1
{
    private Mock<IDisposable> _s;
    private Example1 _example1;
    [SetUp]
    public void SetUp()
    {
        var a = default (int);
        var str = default (string);
        s = new IDisposable();
        _example1 = new Example1(s, a, str);
    }

    [Test]
    public void Function1()
    {
        var d = default (int);
        var e = default (int);
        var actual = Function1(d, e);
        var expected = default (int);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Function2();
        Assert.Fail("autogenerated");
    }
}