using System;
using NUnit.Framework;

[TestFixture]
class Example2
{
    private Example2 _example2;
    [SetUp]
    public void SetUp()
    {
        _example2 = new Example2();
    }

    [Test]
    public void Function1()
    {
        Function1();
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Function2();
        Assert.Fail("autogenerated");
    }
}