using System;
using NUnit.Framework;

[TestFixture]
class Example1
{
    private Mock<IDisposable> _s;
    private Example1 _example1;
    [Test]
    public void Function1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Assert.Fail("autogenerated");
    }
}