using System;
using NUnit.Framework;

[TestFixture]
class Example2
{
    private Example2 _example2;
    [Test]
    public void Function1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        Assert.Fail("autogenerated");
    }
}