using System;
using NUnit.Framework;

[Test]
class Example2
{
    public void Function1()
    {
        Assert.Fail("autogenerated");
    }

    public void Function2()
    {
        Assert.Fail("autogenerated");
    }
}